class DeployError(Exception):
    """Base for all CLI-rendered errors."""

class ConfigError(DeployError): ...
class UnknownAliasError(ConfigError): ...
class AWSAuthError(DeployError): ...
class PipelineNotFoundError(DeployError): ...
class ApprovalTimeoutError(DeployError): ...
class ExecutionFailedError(DeployError): ...
class ConcurrencyError(DeployError): ...
